---
abstract: 'Moose implemention of the Interactive Brokers callback.'
author:
  - 'Doug Spencer, C<< <forhire99 at gmail.com> >>'
  - 'Doug Spencer <forhire99@gmail.com>'
build_requires:
  Data::Dumper: 0
  Date::Manip: 0
  ExtUtils::MakeMaker: 6.59
  Finance::InteractiveBrokers::TWS: 0
  MooseX::Declare: 0
  MooseX::Types: 0
  MooseX::Types::Moose: 0
  MooseX::Types::URI: 0
  Test::More: 0
  Time::HiRes::Value: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
  Module::Install: 0
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: artistic2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-IBrokers-MooseCallback
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Finance-IBrokers-MooseCallback
  license: http://www.perlfoundation.org/artistic_license_2_0
version: 0.02
